fix TypeError when segment size exceeds DEFAULT_MAX_FILE_SIZE (#591)
fix TypeError when segment size exceeds DEFAULT_MAX_FILE_SIZE

Fix for "TypeError: 'float' object cannot be interpreted as an integer" in sdk/obs/v1/_proxy.py when the specified segment_size exceeds the DEFAULT_MAX_FILE_SIZE.
The TypeError is caused because DEFAULT_MAX_FILE_SIZE is a float, but should be an int:
>>> import otcextensions
>>> otcextensions.sdk.obs.v1._proxy.DEFAULT_MAX_FILE_SIZE
2684354561.0

Traceback (most recent call last):
File "", line 1, in 
File "/var/lib/linux/git/python-otcextensions/otcextensions/sdk/obs/v1/_proxy.py", line 415, in create_object
self._upload_large_object(
File "/var/lib/linux/git/python-otcextensions/otcextensions/sdk/obs/v1/_proxy.py", line 451, in _upload_large_object
segments = utils._get_file_segments(
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/var/lib/linux/git/python-otcextensions/otcextensions/common/utils.py", line 118, in _get_file_segments
for (index, offset) in enumerate(range(0, file_size, segment_size)):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'float' object cannot be interpreted as an integer

Reviewed-by: Vineet Pruthi
Reviewed-by: Tino Schr